// Command gen-constants generates LibRaw constants from fixture headers.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type enumDecl struct {
	Name    string
	Members []memberDecl
}

type memberDecl struct {
	Name  string
	Value string
}

var (
	enumRE  = regexp.MustCompile(`(?s)enum\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{(.*?)\};`)
	macroRE = regexp.MustCompile(`(?m)^[ \t]*#[ \t]*define[ \t]+(LIBRAW_[A-Za-z0-9_]+)(\([^)]*\))?[ \t]*(.*)$`)
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	headerPath := filepath.Join("testdata", "headers", "libraw", "libraw_const.h")
	body, err := os.ReadFile(headerPath)
	if err != nil {
		return err
	}

	clean := stripComments(string(body))
	enums := parseEnums(clean)
	macros := parseMacros(clean, enums)
	var out bytes.Buffer
	out.WriteString("// Code generated by tools/gen-constants; DO NOT EDIT.\n\n")
	out.WriteString("package libraw\n\n")

	out.WriteString("const (\n")
	out.WriteString("\tLIBRAW_MAJOR_VERSION = 0\n")
	out.WriteString("\tLIBRAW_MINOR_VERSION = 22\n")
	out.WriteString("\tLIBRAW_PATCH_VERSION = 1\n")
	out.WriteString("\tLIBRAW_VERSION = ((LIBRAW_MAJOR_VERSION << 16) | (LIBRAW_MINOR_VERSION << 8) | LIBRAW_PATCH_VERSION)\n")
	out.WriteString("\tLIBRAW_SHLIB_CURRENT = 25\n")
	out.WriteString("\tLIBRAW_SHLIB_REVISION = 0\n")
	out.WriteString("\tLIBRAW_SHLIB_AGE = 0\n")
	out.WriteString(")\n\n")

	out.WriteString("// LibRaw macro constants mirror public LIBRAW_* macros.\n")
	out.WriteString("const (\n")
	for _, macro := range macros {
		fmt.Fprintf(&out, "\t%s = %s\n", macro.Name, macro.Value)
	}
	out.WriteString(")\n\n")

	for _, enum := range enums {
		fmt.Fprintf(&out, "// %s constants mirror LibRaw enum %s.\n", enumType(enum.Name), enum.Name)
		out.WriteString("const (\n")
		for _, member := range enum.Members {
			fmt.Fprintf(&out, "\t%s %s = %s\n", member.Name, enumType(enum.Name), member.Value)
		}
		out.WriteString(")\n\n")
	}

	if err := os.WriteFile("constants_generated.go", out.Bytes(), 0o644); err != nil {
		return err
	}
	return nil
}

func parseEnums(body string) []enumDecl {
	var enums []enumDecl
	for _, match := range enumRE.FindAllStringSubmatch(body, -1) {
		if len(match) < 3 {
			continue
		}
		members := parseMembers(match[2])
		if len(members) == 0 {
			continue
		}
		enums = append(enums, enumDecl{Name: match[1], Members: members})
	}
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })
	return enums
}

func parseMacros(body string, enums []enumDecl) []memberDecl {
	enumMembers := map[string]struct{}{}
	for _, enum := range enums {
		for _, member := range enum.Members {
			enumMembers[member.Name] = struct{}{}
		}
	}

	seen := map[string]struct{}{}
	var macros []memberDecl
	for _, match := range macroRE.FindAllStringSubmatch(body, -1) {
		if len(match) < 4 {
			continue
		}
		name := match[1]
		params := match[2]
		value := cleanValue(match[3])
		if params != "" || value == "" || strings.HasPrefix(value, "#") {
			continue
		}
		if _, ok := enumMembers[name]; ok {
			continue
		}
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		macros = append(macros, memberDecl{Name: name, Value: value})
	}
	sort.Slice(macros, func(i, j int) bool { return macros[i].Name < macros[j].Name })
	return macros
}

func parseMembers(body string) []memberDecl {
	var members []memberDecl
	previous := ""
	for _, raw := range strings.Split(body, ",") {
		part := strings.TrimSpace(raw)
		if part == "" {
			continue
		}
		value := ""
		if idx := strings.Index(part, "="); idx >= 0 {
			value = cleanValue(part[idx+1:])
			part = strings.TrimSpace(part[:idx])
		}
		fields := strings.Fields(part)
		if len(fields) == 0 {
			continue
		}
		name := fields[0]
		if !isIdentifier(name) {
			continue
		}
		if value == "" {
			if previous == "" {
				value = "0"
			} else {
				value = previous + " + 1"
			}
		}
		members = append(members, memberDecl{Name: name, Value: value})
		previous = name
	}
	return members
}

func cleanValue(value string) string {
	value = strings.TrimSpace(value)
	value = strings.TrimSuffix(value, "\\")
	value = strings.TrimSpace(value)
	intSuffixRE := regexp.MustCompile(`(?i)(\b(?:0x[0-9a-f]+|[0-9]+))(?:ULL|LL|UL|U|L)\b`)
	floatSuffixRE := regexp.MustCompile(`(?i)(\b[0-9]+(?:\.[0-9]+)?)(?:f)\b`)
	value = intSuffixRE.ReplaceAllString(value, "$1")
	value = floatSuffixRE.ReplaceAllString(value, "$1")
	return value
}

func enumType(name string) string {
	switch name {
	case "LibRaw_errors":
		return "ErrorCode"
	case "LibRaw_progress":
		return "Progress"
	default:
		return "int"
	}
}

func stripComments(in string) string {
	blockRE := regexp.MustCompile(`(?s)/\*.*?\*/`)
	lineRE := regexp.MustCompile(`(?m)//.*$`)
	return lineRE.ReplaceAllString(blockRE.ReplaceAllString(in, ""), "")
}

func isIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if i == 0 {
			if r != '_' && (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') {
				return false
			}
			continue
		}
		if r != '_' && (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') {
			return false
		}
	}
	return true
}
