// Code generated by tools/gen-constants; DO NOT EDIT.

package libraw

const (
	LIBRAW_MAJOR_VERSION  = 0
	LIBRAW_MINOR_VERSION  = 22
	LIBRAW_PATCH_VERSION  = 1
	LIBRAW_VERSION        = ((LIBRAW_MAJOR_VERSION << 16) | (LIBRAW_MINOR_VERSION << 8) | LIBRAW_PATCH_VERSION)
	LIBRAW_SHLIB_CURRENT  = 25
	LIBRAW_SHLIB_REVISION = 0
	LIBRAW_SHLIB_AGE      = 0
)

// LibRaw macro constants mirror public LIBRAW_* macros.
const (
	LIBRAW_AFDATA_MAXCOUNT                   = 4
	LIBRAW_AHD_TILE                          = 512
	LIBRAW_CBLACK_SIZE                       = 4104
	LIBRAW_CRXTRACKS_MAXCOUNT                = 16
	LIBRAW_DEFAULT_ADJUST_MAXIMUM_THRESHOLD  = 0.75
	LIBRAW_DEFAULT_AUTO_BRIGHTNESS_THRESHOLD = 0.01
	LIBRAW_EXIFTOOLTAGTYPE_binary            = LIBRAW_EXIFTAG_TYPE_UNDEFINED
	LIBRAW_EXIFTOOLTAGTYPE_complex           = LIBRAW_EXIFTAG_TYPE_COMPLEX
	LIBRAW_EXIFTOOLTAGTYPE_double            = LIBRAW_EXIFTAG_TYPE_DOUBLE
	LIBRAW_EXIFTOOLTAGTYPE_float             = LIBRAW_EXIFTAG_TYPE_FLOAT
	LIBRAW_EXIFTOOLTAGTYPE_ifd               = LIBRAW_EXIFTAG_TYPE_IFD
	LIBRAW_EXIFTOOLTAGTYPE_ifd64             = LIBRAW_EXIFTAG_TYPE_IFD8
	LIBRAW_EXIFTOOLTAGTYPE_int16s            = LIBRAW_EXIFTAG_TYPE_SSHORT
	LIBRAW_EXIFTOOLTAGTYPE_int16u            = LIBRAW_EXIFTAG_TYPE_SHORT
	LIBRAW_EXIFTOOLTAGTYPE_int32s            = LIBRAW_EXIFTAG_TYPE_SLONG
	LIBRAW_EXIFTOOLTAGTYPE_int32u            = LIBRAW_EXIFTAG_TYPE_LONG
	LIBRAW_EXIFTOOLTAGTYPE_int64s            = LIBRAW_EXIFTAG_TYPE_SLONG8
	LIBRAW_EXIFTOOLTAGTYPE_int64u            = LIBRAW_EXIFTAG_TYPE_LONG8
	LIBRAW_EXIFTOOLTAGTYPE_int8s             = LIBRAW_EXIFTAG_TYPE_SBYTE
	LIBRAW_EXIFTOOLTAGTYPE_int8u             = LIBRAW_EXIFTAG_TYPE_BYTE
	LIBRAW_EXIFTOOLTAGTYPE_rational64s       = LIBRAW_EXIFTAG_TYPE_SRATIONAL
	LIBRAW_EXIFTOOLTAGTYPE_rational64u       = LIBRAW_EXIFTAG_TYPE_RATIONAL
	LIBRAW_EXIFTOOLTAGTYPE_string            = LIBRAW_EXIFTAG_TYPE_ASCII
	LIBRAW_EXIFTOOLTAGTYPE_undef             = LIBRAW_EXIFTAG_TYPE_UNDEFINED
	LIBRAW_EXIFTOOLTAGTYPE_unicode           = LIBRAW_EXIFTAG_TYPE_UNICODE
	LIBRAW_IFD_MAXCOUNT                      = 10
	LIBRAW_LENS_NOT_SET                      = 0xffffffffffffffff
	LIBRAW_MAX_ALLOC_MB_DEFAULT              = 2048
	LIBRAW_MAX_CR3_RAW_FILE_SIZE             = LIBRAW_MAX_NONDNG_RAW_FILE_SIZE
	LIBRAW_MAX_DNG_RAW_FILE_SIZE             = 4294967295
	LIBRAW_MAX_METADATA_BLOCKS               = 1024
	LIBRAW_MAX_NONDNG_RAW_FILE_SIZE          = 2147483647
	LIBRAW_MAX_PROFILE_SIZE_MB               = 256
	LIBRAW_MAX_THUMBNAIL_MB                  = 512
	LIBRAW_PROGRESS_THUMB_MASK               = 0x0fffffff
	LIBRAW_THUMBNAIL_MAXCOUNT                = 8
	LIBRAW_X3F_ALLOC_LIMIT_MB                = 512
	LIBRAW_XTRANS                            = 9
)

// int constants mirror LibRaw enum LIBRAW_SONY_FOCUSMODEmodes.
const (
	LIBRAW_SONY_FOCUSMODE_MF           int = 0
	LIBRAW_SONY_FOCUSMODE_AF_S         int = 2
	LIBRAW_SONY_FOCUSMODE_AF_C         int = 3
	LIBRAW_SONY_FOCUSMODE_AF_A         int = 4
	LIBRAW_SONY_FOCUSMODE_DMF          int = 6
	LIBRAW_SONY_FOCUSMODE_AF_D         int = 7
	LIBRAW_SONY_FOCUSMODE_AF           int = 101
	LIBRAW_SONY_FOCUSMODE_PERMANENT_AF int = 104
	LIBRAW_SONY_FOCUSMODE_SEMI_MF      int = 105
	LIBRAW_SONY_FOCUSMODE_UNKNOWN      int = -1
)

// int constants mirror LibRaw enum LibRawImageAspects.
const (
	LIBRAW_IMAGE_ASPECT_UNKNOWN                   int = 0
	LIBRAW_IMAGE_ASPECT_OTHER                     int = 1
	LIBRAW_IMAGE_ASPECT_MINIMAL_REAL_ASPECT_VALUE int = 99
	LIBRAW_IMAGE_ASPECT_MAXIMAL_REAL_ASPECT_VALUE int = 10000
	LIBRAW_IMAGE_ASPECT_3to2                      int = (1000 * 3) / 2
	LIBRAW_IMAGE_ASPECT_1to1                      int = 1000
	LIBRAW_IMAGE_ASPECT_4to3                      int = (1000 * 4) / 3
	LIBRAW_IMAGE_ASPECT_16to9                     int = (1000 * 16) / 9
	LIBRAW_IMAGE_ASPECT_5to4                      int = (1000 * 5) / 4
	LIBRAW_IMAGE_ASPECT_7to6                      int = (1000 * 7) / 6
	LIBRAW_IMAGE_ASPECT_6to5                      int = (1000 * 6) / 5
	LIBRAW_IMAGE_ASPECT_7to5                      int = (1000 * 7) / 5
)

// int constants mirror LibRaw enum LibRaw_As_Shot_WB_Applied_codes.
const (
	LIBRAW_ASWB_APPLIED    int = 1
	LIBRAW_ASWB_CANON      int = 2
	LIBRAW_ASWB_NIKON      int = 4
	LIBRAW_ASWB_NIKON_SRAW int = 8
	LIBRAW_ASWB_PENTAX     int = 16
	LIBRAW_ASWB_SONY       int = 32
)

// int constants mirror LibRaw enum LibRaw_Canon_RecordModes.
const (
	LIBRAW_Canon_RecordMode_UNDEFINED  int = 0
	LIBRAW_Canon_RecordMode_JPEG       int = LIBRAW_Canon_RecordMode_UNDEFINED + 1
	LIBRAW_Canon_RecordMode_CRW_THM    int = LIBRAW_Canon_RecordMode_JPEG + 1
	LIBRAW_Canon_RecordMode_AVI_THM    int = LIBRAW_Canon_RecordMode_CRW_THM + 1
	LIBRAW_Canon_RecordMode_TIF        int = LIBRAW_Canon_RecordMode_AVI_THM + 1
	LIBRAW_Canon_RecordMode_TIF_JPEG   int = LIBRAW_Canon_RecordMode_TIF + 1
	LIBRAW_Canon_RecordMode_CR2        int = LIBRAW_Canon_RecordMode_TIF_JPEG + 1
	LIBRAW_Canon_RecordMode_CR2_JPEG   int = LIBRAW_Canon_RecordMode_CR2 + 1
	LIBRAW_Canon_RecordMode_UNKNOWN    int = LIBRAW_Canon_RecordMode_CR2_JPEG + 1
	LIBRAW_Canon_RecordMode_MOV        int = LIBRAW_Canon_RecordMode_UNKNOWN + 1
	LIBRAW_Canon_RecordMode_MP4        int = LIBRAW_Canon_RecordMode_MOV + 1
	LIBRAW_Canon_RecordMode_CRM        int = LIBRAW_Canon_RecordMode_MP4 + 1
	LIBRAW_Canon_RecordMode_CR3        int = LIBRAW_Canon_RecordMode_CRM + 1
	LIBRAW_Canon_RecordMode_CR3_JPEG   int = LIBRAW_Canon_RecordMode_CR3 + 1
	LIBRAW_Canon_RecordMode_HEIF       int = LIBRAW_Canon_RecordMode_CR3_JPEG + 1
	LIBRAW_Canon_RecordMode_CR3_HEIF   int = LIBRAW_Canon_RecordMode_HEIF + 1
	LIBRAW_Canon_RecordMode_TheLastOne int = LIBRAW_Canon_RecordMode_CR3_HEIF + 1
)

// int constants mirror LibRaw enum LibRaw_ExifTagTypes.
const (
	LIBRAW_EXIFTAG_TYPE_UNKNOWN   int = 0
	LIBRAW_EXIFTAG_TYPE_BYTE      int = 1
	LIBRAW_EXIFTAG_TYPE_ASCII     int = 2
	LIBRAW_EXIFTAG_TYPE_SHORT     int = 3
	LIBRAW_EXIFTAG_TYPE_LONG      int = 4
	LIBRAW_EXIFTAG_TYPE_RATIONAL  int = 5
	LIBRAW_EXIFTAG_TYPE_SBYTE     int = 6
	LIBRAW_EXIFTAG_TYPE_UNDEFINED int = 7
	LIBRAW_EXIFTAG_TYPE_SSHORT    int = 8
	LIBRAW_EXIFTAG_TYPE_SLONG     int = 9
	LIBRAW_EXIFTAG_TYPE_SRATIONAL int = 10
	LIBRAW_EXIFTAG_TYPE_FLOAT     int = 11
	LIBRAW_EXIFTAG_TYPE_DOUBLE    int = 12
	LIBRAW_EXIFTAG_TYPE_IFD       int = 13
	LIBRAW_EXIFTAG_TYPE_UNICODE   int = 14
	LIBRAW_EXIFTAG_TYPE_COMPLEX   int = 15
	LIBRAW_EXIFTAG_TYPE_LONG8     int = 16
	LIBRAW_EXIFTAG_TYPE_SLONG8    int = 17
	LIBRAW_EXIFTAG_TYPE_IFD8      int = 18
)

// int constants mirror LibRaw enum LibRaw_HasselbladFormatCodes.
const (
	LIBRAW_HF_Unknown                int = 0
	LIBRAW_HF_3FR                    int = LIBRAW_HF_Unknown + 1
	LIBRAW_HF_FFF                    int = LIBRAW_HF_3FR + 1
	LIBRAW_HF_Imacon                 int = LIBRAW_HF_FFF + 1
	LIBRAW_HF_HasselbladDNG          int = LIBRAW_HF_Imacon + 1
	LIBRAW_HF_AdobeDNG               int = LIBRAW_HF_HasselbladDNG + 1
	LIBRAW_HF_AdobeDNG_fromPhocusDNG int = LIBRAW_HF_AdobeDNG + 1
)

// int constants mirror LibRaw enum LibRaw_KodakSensors.
const (
	LIBRAW_Kodak_UnknownSensor int = 0
	LIBRAW_Kodak_M1            int = 1
	LIBRAW_Kodak_M15           int = 2
	LIBRAW_Kodak_M16           int = 3
	LIBRAW_Kodak_M17           int = 4
	LIBRAW_Kodak_M2            int = 5
	LIBRAW_Kodak_M23           int = 6
	LIBRAW_Kodak_M24           int = 7
	LIBRAW_Kodak_M3            int = 8
	LIBRAW_Kodak_M5            int = 9
	LIBRAW_Kodak_M6            int = 10
	LIBRAW_Kodak_C14           int = 11
	LIBRAW_Kodak_X14           int = 12
	LIBRAW_Kodak_M11           int = 13
)

// int constants mirror LibRaw enum LibRaw_MultiExposure_related.
const (
	LIBRAW_ME_NONE    int = 0
	LIBRAW_ME_SIMPLE  int = 1
	LIBRAW_ME_OVERLAY int = 2
	LIBRAW_ME_HDR     int = 3
)

// int constants mirror LibRaw enum LibRaw_Sony_0x2010_Type.
const (
	LIBRAW_SONY_Tag2010None int = 0
	LIBRAW_SONY_Tag2010a    int = LIBRAW_SONY_Tag2010None + 1
	LIBRAW_SONY_Tag2010b    int = LIBRAW_SONY_Tag2010a + 1
	LIBRAW_SONY_Tag2010c    int = LIBRAW_SONY_Tag2010b + 1
	LIBRAW_SONY_Tag2010d    int = LIBRAW_SONY_Tag2010c + 1
	LIBRAW_SONY_Tag2010e    int = LIBRAW_SONY_Tag2010d + 1
	LIBRAW_SONY_Tag2010f    int = LIBRAW_SONY_Tag2010e + 1
	LIBRAW_SONY_Tag2010g    int = LIBRAW_SONY_Tag2010f + 1
	LIBRAW_SONY_Tag2010h    int = LIBRAW_SONY_Tag2010g + 1
	LIBRAW_SONY_Tag2010i    int = LIBRAW_SONY_Tag2010h + 1
)

// int constants mirror LibRaw enum LibRaw_Sony_0x9050_Type.
const (
	LIBRAW_SONY_Tag9050None int = 0
	LIBRAW_SONY_Tag9050a    int = LIBRAW_SONY_Tag9050None + 1
	LIBRAW_SONY_Tag9050b    int = LIBRAW_SONY_Tag9050a + 1
	LIBRAW_SONY_Tag9050c    int = LIBRAW_SONY_Tag9050b + 1
	LIBRAW_SONY_Tag9050d    int = LIBRAW_SONY_Tag9050c + 1
)

// int constants mirror LibRaw enum LibRaw_camera_formats.
const (
	LIBRAW_FORMAT_Unknown      int = 0
	LIBRAW_FORMAT_APSC         int = LIBRAW_FORMAT_Unknown + 1
	LIBRAW_FORMAT_FF           int = LIBRAW_FORMAT_APSC + 1
	LIBRAW_FORMAT_MF           int = LIBRAW_FORMAT_FF + 1
	LIBRAW_FORMAT_APSH         int = LIBRAW_FORMAT_MF + 1
	LIBRAW_FORMAT_1INCH        int = LIBRAW_FORMAT_APSH + 1
	LIBRAW_FORMAT_1div2p3INCH  int = LIBRAW_FORMAT_1INCH + 1
	LIBRAW_FORMAT_1div1p7INCH  int = LIBRAW_FORMAT_1div2p3INCH + 1
	LIBRAW_FORMAT_FT           int = LIBRAW_FORMAT_1div1p7INCH + 1
	LIBRAW_FORMAT_CROP645      int = LIBRAW_FORMAT_FT + 1
	LIBRAW_FORMAT_LeicaS       int = LIBRAW_FORMAT_CROP645 + 1
	LIBRAW_FORMAT_645          int = LIBRAW_FORMAT_LeicaS + 1
	LIBRAW_FORMAT_66           int = LIBRAW_FORMAT_645 + 1
	LIBRAW_FORMAT_69           int = LIBRAW_FORMAT_66 + 1
	LIBRAW_FORMAT_LF           int = LIBRAW_FORMAT_69 + 1
	LIBRAW_FORMAT_Leica_DMR    int = LIBRAW_FORMAT_LF + 1
	LIBRAW_FORMAT_67           int = LIBRAW_FORMAT_Leica_DMR + 1
	LIBRAW_FORMAT_SigmaAPSC    int = LIBRAW_FORMAT_67 + 1
	LIBRAW_FORMAT_SigmaMerrill int = LIBRAW_FORMAT_SigmaAPSC + 1
	LIBRAW_FORMAT_SigmaAPSH    int = LIBRAW_FORMAT_SigmaMerrill + 1
	LIBRAW_FORMAT_3648         int = LIBRAW_FORMAT_SigmaAPSH + 1
	LIBRAW_FORMAT_68           int = LIBRAW_FORMAT_3648 + 1
	LIBRAW_FORMAT_TheLastOne   int = LIBRAW_FORMAT_68 + 1
)

// int constants mirror LibRaw enum LibRaw_camera_mounts.
const (
	LIBRAW_MOUNT_Unknown         int = 0
	LIBRAW_MOUNT_Alpa            int = LIBRAW_MOUNT_Unknown + 1
	LIBRAW_MOUNT_C               int = LIBRAW_MOUNT_Alpa + 1
	LIBRAW_MOUNT_Canon_EF_M      int = LIBRAW_MOUNT_C + 1
	LIBRAW_MOUNT_Canon_EF_S      int = LIBRAW_MOUNT_Canon_EF_M + 1
	LIBRAW_MOUNT_Canon_EF        int = LIBRAW_MOUNT_Canon_EF_S + 1
	LIBRAW_MOUNT_Canon_RF        int = LIBRAW_MOUNT_Canon_EF + 1
	LIBRAW_MOUNT_Contax_N        int = LIBRAW_MOUNT_Canon_RF + 1
	LIBRAW_MOUNT_Contax645       int = LIBRAW_MOUNT_Contax_N + 1
	LIBRAW_MOUNT_FT              int = LIBRAW_MOUNT_Contax645 + 1
	LIBRAW_MOUNT_mFT             int = LIBRAW_MOUNT_FT + 1
	LIBRAW_MOUNT_Fuji_GF         int = LIBRAW_MOUNT_mFT + 1
	LIBRAW_MOUNT_Fuji_GX         int = LIBRAW_MOUNT_Fuji_GF + 1
	LIBRAW_MOUNT_Fuji_X          int = LIBRAW_MOUNT_Fuji_GX + 1
	LIBRAW_MOUNT_Hasselblad_H    int = LIBRAW_MOUNT_Fuji_X + 1
	LIBRAW_MOUNT_Hasselblad_V    int = LIBRAW_MOUNT_Hasselblad_H + 1
	LIBRAW_MOUNT_Hasselblad_XCD  int = LIBRAW_MOUNT_Hasselblad_V + 1
	LIBRAW_MOUNT_Leica_M         int = LIBRAW_MOUNT_Hasselblad_XCD + 1
	LIBRAW_MOUNT_Leica_R         int = LIBRAW_MOUNT_Leica_M + 1
	LIBRAW_MOUNT_Leica_S         int = LIBRAW_MOUNT_Leica_R + 1
	LIBRAW_MOUNT_Leica_SL        int = LIBRAW_MOUNT_Leica_S + 1
	LIBRAW_MOUNT_Leica_TL        int = LIBRAW_MOUNT_Leica_SL + 1
	LIBRAW_MOUNT_LPS_L           int = LIBRAW_MOUNT_Leica_TL + 1
	LIBRAW_MOUNT_Mamiya67        int = LIBRAW_MOUNT_LPS_L + 1
	LIBRAW_MOUNT_Mamiya645       int = LIBRAW_MOUNT_Mamiya67 + 1
	LIBRAW_MOUNT_Minolta_A       int = LIBRAW_MOUNT_Mamiya645 + 1
	LIBRAW_MOUNT_Nikon_CX        int = LIBRAW_MOUNT_Minolta_A + 1
	LIBRAW_MOUNT_Nikon_F         int = LIBRAW_MOUNT_Nikon_CX + 1
	LIBRAW_MOUNT_Nikon_Z         int = LIBRAW_MOUNT_Nikon_F + 1
	LIBRAW_MOUNT_PhaseOne_iXM_MV int = LIBRAW_MOUNT_Nikon_Z + 1
	LIBRAW_MOUNT_PhaseOne_iXM_RS int = LIBRAW_MOUNT_PhaseOne_iXM_MV + 1
	LIBRAW_MOUNT_PhaseOne_iXM    int = LIBRAW_MOUNT_PhaseOne_iXM_RS + 1
	LIBRAW_MOUNT_Pentax_645      int = LIBRAW_MOUNT_PhaseOne_iXM + 1
	LIBRAW_MOUNT_Pentax_K        int = LIBRAW_MOUNT_Pentax_645 + 1
	LIBRAW_MOUNT_Pentax_Q        int = LIBRAW_MOUNT_Pentax_K + 1
	LIBRAW_MOUNT_RicohModule     int = LIBRAW_MOUNT_Pentax_Q + 1
	LIBRAW_MOUNT_Rollei_bayonet  int = LIBRAW_MOUNT_RicohModule + 1
	LIBRAW_MOUNT_Samsung_NX_M    int = LIBRAW_MOUNT_Rollei_bayonet + 1
	LIBRAW_MOUNT_Samsung_NX      int = LIBRAW_MOUNT_Samsung_NX_M + 1
	LIBRAW_MOUNT_Sigma_X3F       int = LIBRAW_MOUNT_Samsung_NX + 1
	LIBRAW_MOUNT_Sony_E          int = LIBRAW_MOUNT_Sigma_X3F + 1
	LIBRAW_MOUNT_LF              int = LIBRAW_MOUNT_Sony_E + 1
	LIBRAW_MOUNT_DigitalBack     int = LIBRAW_MOUNT_LF + 1
	LIBRAW_MOUNT_FixedLens       int = LIBRAW_MOUNT_DigitalBack + 1
	LIBRAW_MOUNT_IL_UM           int = LIBRAW_MOUNT_FixedLens + 1
	LIBRAW_MOUNT_TheLastOne      int = LIBRAW_MOUNT_IL_UM + 1
)

// int constants mirror LibRaw enum LibRaw_cameramaker_index.
const (
	LIBRAW_CAMERAMAKER_Unknown      int = 0
	LIBRAW_CAMERAMAKER_Agfa         int = LIBRAW_CAMERAMAKER_Unknown + 1
	LIBRAW_CAMERAMAKER_Alcatel      int = LIBRAW_CAMERAMAKER_Agfa + 1
	LIBRAW_CAMERAMAKER_Apple        int = LIBRAW_CAMERAMAKER_Alcatel + 1
	LIBRAW_CAMERAMAKER_Aptina       int = LIBRAW_CAMERAMAKER_Apple + 1
	LIBRAW_CAMERAMAKER_AVT          int = LIBRAW_CAMERAMAKER_Aptina + 1
	LIBRAW_CAMERAMAKER_Baumer       int = LIBRAW_CAMERAMAKER_AVT + 1
	LIBRAW_CAMERAMAKER_Broadcom     int = LIBRAW_CAMERAMAKER_Baumer + 1
	LIBRAW_CAMERAMAKER_Canon        int = LIBRAW_CAMERAMAKER_Broadcom + 1
	LIBRAW_CAMERAMAKER_Casio        int = LIBRAW_CAMERAMAKER_Canon + 1
	LIBRAW_CAMERAMAKER_CINE         int = LIBRAW_CAMERAMAKER_Casio + 1
	LIBRAW_CAMERAMAKER_Clauss       int = LIBRAW_CAMERAMAKER_CINE + 1
	LIBRAW_CAMERAMAKER_Contax       int = LIBRAW_CAMERAMAKER_Clauss + 1
	LIBRAW_CAMERAMAKER_Creative     int = LIBRAW_CAMERAMAKER_Contax + 1
	LIBRAW_CAMERAMAKER_DJI          int = LIBRAW_CAMERAMAKER_Creative + 1
	LIBRAW_CAMERAMAKER_DXO          int = LIBRAW_CAMERAMAKER_DJI + 1
	LIBRAW_CAMERAMAKER_Epson        int = LIBRAW_CAMERAMAKER_DXO + 1
	LIBRAW_CAMERAMAKER_Foculus      int = LIBRAW_CAMERAMAKER_Epson + 1
	LIBRAW_CAMERAMAKER_Fujifilm     int = LIBRAW_CAMERAMAKER_Foculus + 1
	LIBRAW_CAMERAMAKER_Generic      int = LIBRAW_CAMERAMAKER_Fujifilm + 1
	LIBRAW_CAMERAMAKER_Gione        int = LIBRAW_CAMERAMAKER_Generic + 1
	LIBRAW_CAMERAMAKER_GITUP        int = LIBRAW_CAMERAMAKER_Gione + 1
	LIBRAW_CAMERAMAKER_Google       int = LIBRAW_CAMERAMAKER_GITUP + 1
	LIBRAW_CAMERAMAKER_GoPro        int = LIBRAW_CAMERAMAKER_Google + 1
	LIBRAW_CAMERAMAKER_Hasselblad   int = LIBRAW_CAMERAMAKER_GoPro + 1
	LIBRAW_CAMERAMAKER_HTC          int = LIBRAW_CAMERAMAKER_Hasselblad + 1
	LIBRAW_CAMERAMAKER_I_Mobile     int = LIBRAW_CAMERAMAKER_HTC + 1
	LIBRAW_CAMERAMAKER_Imacon       int = LIBRAW_CAMERAMAKER_I_Mobile + 1
	LIBRAW_CAMERAMAKER_JK_Imaging   int = LIBRAW_CAMERAMAKER_Imacon + 1
	LIBRAW_CAMERAMAKER_Kodak        int = LIBRAW_CAMERAMAKER_JK_Imaging + 1
	LIBRAW_CAMERAMAKER_Konica       int = LIBRAW_CAMERAMAKER_Kodak + 1
	LIBRAW_CAMERAMAKER_Leaf         int = LIBRAW_CAMERAMAKER_Konica + 1
	LIBRAW_CAMERAMAKER_Leica        int = LIBRAW_CAMERAMAKER_Leaf + 1
	LIBRAW_CAMERAMAKER_Lenovo       int = LIBRAW_CAMERAMAKER_Leica + 1
	LIBRAW_CAMERAMAKER_LG           int = LIBRAW_CAMERAMAKER_Lenovo + 1
	LIBRAW_CAMERAMAKER_Logitech     int = LIBRAW_CAMERAMAKER_LG + 1
	LIBRAW_CAMERAMAKER_Mamiya       int = LIBRAW_CAMERAMAKER_Logitech + 1
	LIBRAW_CAMERAMAKER_Matrix       int = LIBRAW_CAMERAMAKER_Mamiya + 1
	LIBRAW_CAMERAMAKER_Meizu        int = LIBRAW_CAMERAMAKER_Matrix + 1
	LIBRAW_CAMERAMAKER_Micron       int = LIBRAW_CAMERAMAKER_Meizu + 1
	LIBRAW_CAMERAMAKER_Minolta      int = LIBRAW_CAMERAMAKER_Micron + 1
	LIBRAW_CAMERAMAKER_Motorola     int = LIBRAW_CAMERAMAKER_Minolta + 1
	LIBRAW_CAMERAMAKER_NGM          int = LIBRAW_CAMERAMAKER_Motorola + 1
	LIBRAW_CAMERAMAKER_Nikon        int = LIBRAW_CAMERAMAKER_NGM + 1
	LIBRAW_CAMERAMAKER_Nokia        int = LIBRAW_CAMERAMAKER_Nikon + 1
	LIBRAW_CAMERAMAKER_Olympus      int = LIBRAW_CAMERAMAKER_Nokia + 1
	LIBRAW_CAMERAMAKER_OmniVison    int = LIBRAW_CAMERAMAKER_Olympus + 1
	LIBRAW_CAMERAMAKER_Panasonic    int = LIBRAW_CAMERAMAKER_OmniVison + 1
	LIBRAW_CAMERAMAKER_Parrot       int = LIBRAW_CAMERAMAKER_Panasonic + 1
	LIBRAW_CAMERAMAKER_Pentax       int = LIBRAW_CAMERAMAKER_Parrot + 1
	LIBRAW_CAMERAMAKER_PhaseOne     int = LIBRAW_CAMERAMAKER_Pentax + 1
	LIBRAW_CAMERAMAKER_PhotoControl int = LIBRAW_CAMERAMAKER_PhaseOne + 1
	LIBRAW_CAMERAMAKER_Photron      int = LIBRAW_CAMERAMAKER_PhotoControl + 1
	LIBRAW_CAMERAMAKER_Pixelink     int = LIBRAW_CAMERAMAKER_Photron + 1
	LIBRAW_CAMERAMAKER_Polaroid     int = LIBRAW_CAMERAMAKER_Pixelink + 1
	LIBRAW_CAMERAMAKER_RED          int = LIBRAW_CAMERAMAKER_Polaroid + 1
	LIBRAW_CAMERAMAKER_Ricoh        int = LIBRAW_CAMERAMAKER_RED + 1
	LIBRAW_CAMERAMAKER_Rollei       int = LIBRAW_CAMERAMAKER_Ricoh + 1
	LIBRAW_CAMERAMAKER_RoverShot    int = LIBRAW_CAMERAMAKER_Rollei + 1
	LIBRAW_CAMERAMAKER_Samsung      int = LIBRAW_CAMERAMAKER_RoverShot + 1
	LIBRAW_CAMERAMAKER_Sigma        int = LIBRAW_CAMERAMAKER_Samsung + 1
	LIBRAW_CAMERAMAKER_Sinar        int = LIBRAW_CAMERAMAKER_Sigma + 1
	LIBRAW_CAMERAMAKER_SMaL         int = LIBRAW_CAMERAMAKER_Sinar + 1
	LIBRAW_CAMERAMAKER_Sony         int = LIBRAW_CAMERAMAKER_SMaL + 1
	LIBRAW_CAMERAMAKER_ST_Micro     int = LIBRAW_CAMERAMAKER_Sony + 1
	LIBRAW_CAMERAMAKER_THL          int = LIBRAW_CAMERAMAKER_ST_Micro + 1
	LIBRAW_CAMERAMAKER_VLUU         int = LIBRAW_CAMERAMAKER_THL + 1
	LIBRAW_CAMERAMAKER_Xiaomi       int = LIBRAW_CAMERAMAKER_VLUU + 1
	LIBRAW_CAMERAMAKER_XIAOYI       int = LIBRAW_CAMERAMAKER_Xiaomi + 1
	LIBRAW_CAMERAMAKER_YI           int = LIBRAW_CAMERAMAKER_XIAOYI + 1
	LIBRAW_CAMERAMAKER_Yuneec       int = LIBRAW_CAMERAMAKER_YI + 1
	LIBRAW_CAMERAMAKER_Zeiss        int = LIBRAW_CAMERAMAKER_Yuneec + 1
	LIBRAW_CAMERAMAKER_OnePlus      int = LIBRAW_CAMERAMAKER_Zeiss + 1
	LIBRAW_CAMERAMAKER_ISG          int = LIBRAW_CAMERAMAKER_OnePlus + 1
	LIBRAW_CAMERAMAKER_VIVO         int = LIBRAW_CAMERAMAKER_ISG + 1
	LIBRAW_CAMERAMAKER_HMD_Global   int = LIBRAW_CAMERAMAKER_VIVO + 1
	LIBRAW_CAMERAMAKER_HUAWEI       int = LIBRAW_CAMERAMAKER_HMD_Global + 1
	LIBRAW_CAMERAMAKER_RaspberryPi  int = LIBRAW_CAMERAMAKER_HUAWEI + 1
	LIBRAW_CAMERAMAKER_OmDigital    int = LIBRAW_CAMERAMAKER_RaspberryPi + 1
	LIBRAW_CAMERAMAKER_TheLastOne   int = LIBRAW_CAMERAMAKER_OmDigital + 1
)

// int constants mirror LibRaw enum LibRaw_colorspace.
const (
	LIBRAW_COLORSPACE_NotFound          int = 0
	LIBRAW_COLORSPACE_sRGB              int = LIBRAW_COLORSPACE_NotFound + 1
	LIBRAW_COLORSPACE_AdobeRGB          int = LIBRAW_COLORSPACE_sRGB + 1
	LIBRAW_COLORSPACE_WideGamutRGB      int = LIBRAW_COLORSPACE_AdobeRGB + 1
	LIBRAW_COLORSPACE_ProPhotoRGB       int = LIBRAW_COLORSPACE_WideGamutRGB + 1
	LIBRAW_COLORSPACE_ICC               int = LIBRAW_COLORSPACE_ProPhotoRGB + 1
	LIBRAW_COLORSPACE_Uncalibrated      int = LIBRAW_COLORSPACE_ICC + 1
	LIBRAW_COLORSPACE_CameraLinearUniWB int = LIBRAW_COLORSPACE_Uncalibrated + 1
	LIBRAW_COLORSPACE_CameraLinear      int = LIBRAW_COLORSPACE_CameraLinearUniWB + 1
	LIBRAW_COLORSPACE_CameraGammaUniWB  int = LIBRAW_COLORSPACE_CameraLinear + 1
	LIBRAW_COLORSPACE_CameraGamma       int = LIBRAW_COLORSPACE_CameraGammaUniWB + 1
	LIBRAW_COLORSPACE_MonochromeLinear  int = LIBRAW_COLORSPACE_CameraGamma + 1
	LIBRAW_COLORSPACE_MonochromeGamma   int = LIBRAW_COLORSPACE_MonochromeLinear + 1
	LIBRAW_COLORSPACE_Rec2020           int = LIBRAW_COLORSPACE_MonochromeGamma + 1
	LIBRAW_COLORSPACE_Unknown           int = 255
)

// int constants mirror LibRaw enum LibRaw_constructor_flags.
const (
	LIBRAW_OPTIONS_NONE                int = 0
	LIBRAW_OPTIONS_NO_DATAERR_CALLBACK int = 1 << 1
	LIBRAW_OPIONS_NO_DATAERR_CALLBACK  int = LIBRAW_OPTIONS_NO_DATAERR_CALLBACK
)

// int constants mirror LibRaw enum LibRaw_decoder_flags.
const (
	LIBRAW_DECODER_HASCURVE            int = 1 << 4
	LIBRAW_DECODER_SONYARW2            int = 1 << 5
	LIBRAW_DECODER_TRYRAWSPEED         int = 1 << 6
	LIBRAW_DECODER_OWNALLOC            int = 1 << 7
	LIBRAW_DECODER_FIXEDMAXC           int = 1 << 8
	LIBRAW_DECODER_ADOBECOPYPIXEL      int = 1 << 9
	LIBRAW_DECODER_LEGACY_WITH_MARGINS int = 1 << 10
	LIBRAW_DECODER_3CHANNEL            int = 1 << 11
	LIBRAW_DECODER_SINAR4SHOT          int = 1 << 11
	LIBRAW_DECODER_FLATDATA            int = 1 << 12
	LIBRAW_DECODER_FLAT_BG2_SWAPPED    int = 1 << 13
	LIBRAW_DECODER_UNSUPPORTED_FORMAT  int = 1 << 14
	LIBRAW_DECODER_NOTSET              int = 1 << 15
	LIBRAW_DECODER_TRYRAWSPEED3        int = 1 << 16
)

// int constants mirror LibRaw enum LibRaw_dng_processing.
const (
	LIBRAW_DNG_NONE    int = 0
	LIBRAW_DNG_FLOAT   int = 1
	LIBRAW_DNG_LINEAR  int = 2
	LIBRAW_DNG_DEFLATE int = 4
	LIBRAW_DNG_XTRANS  int = 8
	LIBRAW_DNG_OTHER   int = 16
	LIBRAW_DNG_8BIT    int = 32
	LIBRAW_DNG_ALL     int = LIBRAW_DNG_FLOAT | LIBRAW_DNG_LINEAR | LIBRAW_DNG_DEFLATE | LIBRAW_DNG_XTRANS |
		LIBRAW_DNG_8BIT | LIBRAW_DNG_OTHER
	LIBRAW_DNG_DEFAULT int = LIBRAW_DNG_FLOAT | LIBRAW_DNG_LINEAR |
		LIBRAW_DNG_DEFLATE | LIBRAW_DNG_8BIT
)

// int constants mirror LibRaw enum LibRaw_dngfields_marks.
const (
	LIBRAW_DNGFM_FORWARDMATRIX       int = 1
	LIBRAW_DNGFM_ILLUMINANT          int = 1 << 1
	LIBRAW_DNGFM_COLORMATRIX         int = 1 << 2
	LIBRAW_DNGFM_CALIBRATION         int = 1 << 3
	LIBRAW_DNGFM_ANALOGBALANCE       int = 1 << 4
	LIBRAW_DNGFM_BLACK               int = 1 << 5
	LIBRAW_DNGFM_WHITE               int = 1 << 6
	LIBRAW_DNGFM_OPCODE2             int = 1 << 7
	LIBRAW_DNGFM_LINTABLE            int = 1 << 8
	LIBRAW_DNGFM_CROPORIGIN          int = 1 << 9
	LIBRAW_DNGFM_CROPSIZE            int = 1 << 10
	LIBRAW_DNGFM_PREVIEWCS           int = 1 << 11
	LIBRAW_DNGFM_ASSHOTNEUTRAL       int = 1 << 12
	LIBRAW_DNGFM_BASELINEEXPOSURE    int = 1 << 13
	LIBRAW_DNGFM_LINEARRESPONSELIMIT int = 1 << 14
	LIBRAW_DNGFM_USERCROP            int = 1 << 15
	LIBRAW_DNGFM_OPCODE1             int = 1 << 16
	LIBRAW_DNGFM_OPCODE3             int = 1 << 17
)

// ErrorCode constants mirror LibRaw enum LibRaw_errors.
const (
	LIBRAW_SUCCESS                           ErrorCode = 0
	LIBRAW_UNSPECIFIED_ERROR                 ErrorCode = -1
	LIBRAW_FILE_UNSUPPORTED                  ErrorCode = -2
	LIBRAW_REQUEST_FOR_NONEXISTENT_IMAGE     ErrorCode = -3
	LIBRAW_OUT_OF_ORDER_CALL                 ErrorCode = -4
	LIBRAW_NO_THUMBNAIL                      ErrorCode = -5
	LIBRAW_UNSUPPORTED_THUMBNAIL             ErrorCode = -6
	LIBRAW_INPUT_CLOSED                      ErrorCode = -7
	LIBRAW_NOT_IMPLEMENTED                   ErrorCode = -8
	LIBRAW_REQUEST_FOR_NONEXISTENT_THUMBNAIL ErrorCode = -9
	LIBRAW_UNSUFFICIENT_MEMORY               ErrorCode = -100007
	LIBRAW_DATA_ERROR                        ErrorCode = -100008
	LIBRAW_IO_ERROR                          ErrorCode = -100009
	LIBRAW_CANCELLED_BY_CALLBACK             ErrorCode = -100010
	LIBRAW_BAD_CROP                          ErrorCode = -100011
	LIBRAW_TOO_BIG                           ErrorCode = -100012
	LIBRAW_MEMPOOL_OVERFLOW                  ErrorCode = -100013
)

// int constants mirror LibRaw enum LibRaw_exceptions.
const (
	LIBRAW_EXCEPTION_NONE                  int = 0
	LIBRAW_EXCEPTION_ALLOC                 int = 1
	LIBRAW_EXCEPTION_DECODE_RAW            int = 2
	LIBRAW_EXCEPTION_DECODE_JPEG           int = 3
	LIBRAW_EXCEPTION_IO_EOF                int = 4
	LIBRAW_EXCEPTION_IO_CORRUPT            int = 5
	LIBRAW_EXCEPTION_CANCELLED_BY_CALLBACK int = 6
	LIBRAW_EXCEPTION_BAD_CROP              int = 7
	LIBRAW_EXCEPTION_IO_BADFILE            int = 8
	LIBRAW_EXCEPTION_DECODE_JPEG2000       int = 9
	LIBRAW_EXCEPTION_TOOBIG                int = 10
	LIBRAW_EXCEPTION_MEMPOOL               int = 11
	LIBRAW_EXCEPTION_UNSUPPORTED_FORMAT    int = 12
)

// int constants mirror LibRaw enum LibRaw_image_formats.
const (
	LIBRAW_IMAGE_JPEG   int = 1
	LIBRAW_IMAGE_BITMAP int = 2
	LIBRAW_IMAGE_JPEGXL int = 3
	LIBRAW_IMAGE_H265   int = 4
)

// int constants mirror LibRaw enum LibRaw_internal_thumbnail_formats.
const (
	LIBRAW_INTERNAL_THUMBNAIL_UNKNOWN     int = 0
	LIBRAW_INTERNAL_THUMBNAIL_KODAK_THUMB int = 1
	LIBRAW_INTERNAL_THUMBNAIL_KODAK_YCBCR int = 2
	LIBRAW_INTERNAL_THUMBNAIL_KODAK_RGB   int = 3
	LIBRAW_INTERNAL_THUMBNAIL_JPEG        int = 4
	LIBRAW_INTERNAL_THUMBNAIL_LAYER       int = LIBRAW_INTERNAL_THUMBNAIL_JPEG + 1
	LIBRAW_INTERNAL_THUMBNAIL_ROLLEI      int = LIBRAW_INTERNAL_THUMBNAIL_LAYER + 1
	LIBRAW_INTERNAL_THUMBNAIL_PPM         int = LIBRAW_INTERNAL_THUMBNAIL_ROLLEI + 1
	LIBRAW_INTERNAL_THUMBNAIL_PPM16       int = LIBRAW_INTERNAL_THUMBNAIL_PPM + 1
	LIBRAW_INTERNAL_THUMBNAIL_X3F         int = LIBRAW_INTERNAL_THUMBNAIL_PPM16 + 1
	LIBRAW_INTERNAL_THUMBNAIL_DNG_YCBCR   int = LIBRAW_INTERNAL_THUMBNAIL_X3F + 1
	LIBRAW_INTERNAL_THUMBNAIL_JPEGXL      int = LIBRAW_INTERNAL_THUMBNAIL_DNG_YCBCR + 1
)

// int constants mirror LibRaw enum LibRaw_lens_focal_types.
const (
	LIBRAW_FT_UNDEFINED                   int = 0
	LIBRAW_FT_PRIME_LENS                  int = 1
	LIBRAW_FT_ZOOM_LENS                   int = 2
	LIBRAW_FT_ZOOM_LENS_CONSTANT_APERTURE int = 3
	LIBRAW_FT_ZOOM_LENS_VARIABLE_APERTURE int = 4
)

// int constants mirror LibRaw enum LibRaw_minolta_bayerpatterns.
const (
	LIBRAW_MINOLTA_RGGB   int = 0x01
	LIBRAW_MINOLTA_G2BRG1 int = 0x04
)

// int constants mirror LibRaw enum LibRaw_minolta_storagemethods.
const (
	LIBRAW_MINOLTA_UNPACKED int = 0x52
	LIBRAW_MINOLTA_PACKED   int = 0x59
)

// int constants mirror LibRaw enum LibRaw_open_flags.
const (
	LIBRAW_OPEN_BIGFILE int = 1
	LIBRAW_OPEN_FILE    int = 1 << 1
)

// int constants mirror LibRaw enum LibRaw_openbayer_patterns.
const (
	LIBRAW_OPENBAYER_RGGB int = 0x94
	LIBRAW_OPENBAYER_BGGR int = 0x16
	LIBRAW_OPENBAYER_GRBG int = 0x61
	LIBRAW_OPENBAYER_GBRG int = 0x49
)

// int constants mirror LibRaw enum LibRaw_output_flags.
const (
	LIBRAW_OUTPUT_FLAGS_NONE    int = 0
	LIBRAW_OUTPUT_FLAGS_PPMMETA int = 1
)

// int constants mirror LibRaw enum LibRaw_processing_options.
const (
	LIBRAW_RAWOPTIONS_PENTAX_PS_ALLFRAMES                   int = 1
	LIBRAW_RAWOPTIONS_CONVERTFLOAT_TO_INT                   int = 1 << 1
	LIBRAW_RAWOPTIONS_ARQ_SKIP_CHANNEL_SWAP                 int = 1 << 2
	LIBRAW_RAWOPTIONS_NO_ROTATE_FOR_KODAK_THUMBNAILS        int = 1 << 3
	LIBRAW_RAWOPTIONS_USE_PPM16_THUMBS                      int = 1 << 5
	LIBRAW_RAWOPTIONS_DONT_CHECK_DNG_ILLUMINANT             int = 1 << 6
	LIBRAW_RAWOPTIONS_DNGSDK_ZEROCOPY                       int = 1 << 7
	LIBRAW_RAWOPTIONS_ZEROFILTERS_FOR_MONOCHROMETIFFS       int = 1 << 8
	LIBRAW_RAWOPTIONS_DNG_ADD_ENHANCED                      int = 1 << 9
	LIBRAW_RAWOPTIONS_DNG_ADD_PREVIEWS                      int = 1 << 10
	LIBRAW_RAWOPTIONS_DNG_PREFER_LARGEST_IMAGE              int = 1 << 11
	LIBRAW_RAWOPTIONS_DNG_STAGE2                            int = 1 << 12
	LIBRAW_RAWOPTIONS_DNG_STAGE3                            int = 1 << 13
	LIBRAW_RAWOPTIONS_DNG_ALLOWSIZECHANGE                   int = 1 << 14
	LIBRAW_RAWOPTIONS_DNG_DISABLEWBADJUST                   int = 1 << 15
	LIBRAW_RAWOPTIONS_PROVIDE_NONSTANDARD_WB                int = 1 << 16
	LIBRAW_RAWOPTIONS_CAMERAWB_FALLBACK_TO_DAYLIGHT         int = 1 << 17
	LIBRAW_RAWOPTIONS_CHECK_THUMBNAILS_KNOWN_VENDORS        int = 1 << 18
	LIBRAW_RAWOPTIONS_CHECK_THUMBNAILS_ALL_VENDORS          int = 1 << 19
	LIBRAW_RAWOPTIONS_DNG_STAGE2_IFPRESENT                  int = 1 << 20
	LIBRAW_RAWOPTIONS_DNG_STAGE3_IFPRESENT                  int = 1 << 21
	LIBRAW_RAWOPTIONS_DNG_ADD_MASKS                         int = 1 << 22
	LIBRAW_RAWOPTIONS_CANON_IGNORE_MAKERNOTES_ROTATION      int = 1 << 23
	LIBRAW_RAWOPTIONS_ALLOW_JPEGXL_PREVIEWS                 int = 1 << 24
	LIBRAW_RAWOPTIONS_CANON_CHECK_CAMERA_AUTO_ROTATION_MODE int = 1 << 26
	LIBRAW_RAWOPTIONS_DNG_STAGE23_IFPRESENT_JPGJXL          int = 1 << 27
)

// Progress constants mirror LibRaw enum LibRaw_progress.
const (
	LIBRAW_PROGRESS_START              Progress = 0
	LIBRAW_PROGRESS_OPEN               Progress = 1
	LIBRAW_PROGRESS_IDENTIFY           Progress = 1 << 1
	LIBRAW_PROGRESS_SIZE_ADJUST        Progress = 1 << 2
	LIBRAW_PROGRESS_LOAD_RAW           Progress = 1 << 3
	LIBRAW_PROGRESS_RAW2_IMAGE         Progress = 1 << 4
	LIBRAW_PROGRESS_REMOVE_ZEROES      Progress = 1 << 5
	LIBRAW_PROGRESS_BAD_PIXELS         Progress = 1 << 6
	LIBRAW_PROGRESS_DARK_FRAME         Progress = 1 << 7
	LIBRAW_PROGRESS_FOVEON_INTERPOLATE Progress = 1 << 8
	LIBRAW_PROGRESS_SCALE_COLORS       Progress = 1 << 9
	LIBRAW_PROGRESS_PRE_INTERPOLATE    Progress = 1 << 10
	LIBRAW_PROGRESS_INTERPOLATE        Progress = 1 << 11
	LIBRAW_PROGRESS_MIX_GREEN          Progress = 1 << 12
	LIBRAW_PROGRESS_MEDIAN_FILTER      Progress = 1 << 13
	LIBRAW_PROGRESS_HIGHLIGHTS         Progress = 1 << 14
	LIBRAW_PROGRESS_FUJI_ROTATE        Progress = 1 << 15
	LIBRAW_PROGRESS_FLIP               Progress = 1 << 16
	LIBRAW_PROGRESS_APPLY_PROFILE      Progress = 1 << 17
	LIBRAW_PROGRESS_CONVERT_RGB        Progress = 1 << 18
	LIBRAW_PROGRESS_STRETCH            Progress = 1 << 19
	LIBRAW_PROGRESS_STAGE20            Progress = 1 << 20
	LIBRAW_PROGRESS_STAGE21            Progress = 1 << 21
	LIBRAW_PROGRESS_STAGE22            Progress = 1 << 22
	LIBRAW_PROGRESS_STAGE23            Progress = 1 << 23
	LIBRAW_PROGRESS_STAGE24            Progress = 1 << 24
	LIBRAW_PROGRESS_STAGE25            Progress = 1 << 25
	LIBRAW_PROGRESS_STAGE26            Progress = 1 << 26
	LIBRAW_PROGRESS_STAGE27            Progress = 1 << 27
	LIBRAW_PROGRESS_THUMB_LOAD         Progress = 1 << 28
	LIBRAW_PROGRESS_TRESERVED1         Progress = 1 << 29
	LIBRAW_PROGRESS_TRESERVED2         Progress = 1 << 30
)

// int constants mirror LibRaw enum LibRaw_rawspecial_t.
const (
	LIBRAW_RAWSPECIAL_SONYARW2_NONE          int = 0
	LIBRAW_RAWSPECIAL_SONYARW2_BASEONLY      int = 1
	LIBRAW_RAWSPECIAL_SONYARW2_DELTAONLY     int = 1 << 1
	LIBRAW_RAWSPECIAL_SONYARW2_DELTAZEROBASE int = 1 << 2
	LIBRAW_RAWSPECIAL_SONYARW2_DELTATOVALUE  int = 1 << 3
	LIBRAW_RAWSPECIAL_SONYARW2_ALLFLAGS      int = LIBRAW_RAWSPECIAL_SONYARW2_BASEONLY +
		LIBRAW_RAWSPECIAL_SONYARW2_DELTAONLY +
		LIBRAW_RAWSPECIAL_SONYARW2_DELTAZEROBASE +
		LIBRAW_RAWSPECIAL_SONYARW2_DELTATOVALUE
	LIBRAW_RAWSPECIAL_NODP2Q_INTERPOLATERG int = 1 << 4
	LIBRAW_RAWSPECIAL_NODP2Q_INTERPOLATEAF int = 1 << 5
	LIBRAW_RAWSPECIAL_SRAW_NO_RGB          int = 1 << 6
	LIBRAW_RAWSPECIAL_SRAW_NO_INTERPOLATE  int = 1 << 7
)

// int constants mirror LibRaw enum LibRaw_rawspeed_bits_t.
const (
	LIBRAW_RAWSPEEDV1_USE           int = 1
	LIBRAW_RAWSPEEDV1_FAILONUNKNOWN int = 1 << 1
	LIBRAW_RAWSPEEDV1_IGNOREERRORS  int = 1 << 2
	LIBRAW_RAWSPEEDV3_USE           int = 1 << 8
	LIBRAW_RAWSPEEDV3_FAILONUNKNOWN int = 1 << 9
	LIBRAW_RAWSPEEDV3_IGNOREERRORS  int = 1 << 10
)

// int constants mirror LibRaw enum LibRaw_runtime_capabilities.
const (
	LIBRAW_CAPS_RAWSPEED      int = 1
	LIBRAW_CAPS_DNGSDK        int = 1 << 1
	LIBRAW_CAPS_GPRSDK        int = 1 << 2
	LIBRAW_CAPS_UNICODEPATHS  int = 1 << 3
	LIBRAW_CAPS_X3FTOOLS      int = 1 << 4
	LIBRAW_CAPS_RPI6BY9       int = 1 << 5
	LIBRAW_CAPS_ZLIB          int = 1 << 6
	LIBRAW_CAPS_JPEG          int = 1 << 7
	LIBRAW_CAPS_RAWSPEED3     int = 1 << 8
	LIBRAW_CAPS_RAWSPEED_BITS int = 1 << 9
)

// int constants mirror LibRaw enum LibRaw_sony_cameratypes.
const (
	LIBRAW_SONY_DSC                int = 1
	LIBRAW_SONY_DSLR               int = 2
	LIBRAW_SONY_NEX                int = 3
	LIBRAW_SONY_SLT                int = 4
	LIBRAW_SONY_ILCE               int = 5
	LIBRAW_SONY_ILCA               int = 6
	LIBRAW_SONY_CameraType_UNKNOWN int = 0xffff
)

// int constants mirror LibRaw enum LibRaw_thumbnail_formats.
const (
	LIBRAW_THUMBNAIL_UNKNOWN  int = 0
	LIBRAW_THUMBNAIL_JPEG     int = 1
	LIBRAW_THUMBNAIL_BITMAP   int = 2
	LIBRAW_THUMBNAIL_BITMAP16 int = 3
	LIBRAW_THUMBNAIL_LAYER    int = 4
	LIBRAW_THUMBNAIL_ROLLEI   int = 5
	LIBRAW_THUMBNAIL_H265     int = 6
	LIBRAW_THUMBNAIL_JPEGXL   int = 7
)

// int constants mirror LibRaw enum LibRaw_warnings.
const (
	LIBRAW_WARN_NONE                  int = 0
	LIBRAW_WARN_BAD_CAMERA_WB         int = 1 << 2
	LIBRAW_WARN_NO_METADATA           int = 1 << 3
	LIBRAW_WARN_NO_JPEGLIB            int = 1 << 4
	LIBRAW_WARN_NO_EMBEDDED_PROFILE   int = 1 << 5
	LIBRAW_WARN_NO_INPUT_PROFILE      int = 1 << 6
	LIBRAW_WARN_BAD_OUTPUT_PROFILE    int = 1 << 7
	LIBRAW_WARN_NO_BADPIXELMAP        int = 1 << 8
	LIBRAW_WARN_BAD_DARKFRAME_FILE    int = 1 << 9
	LIBRAW_WARN_BAD_DARKFRAME_DIM     int = 1 << 10
	LIBRAW_WARN_RAWSPEED_PROBLEM      int = 1 << 12
	LIBRAW_WARN_RAWSPEED_UNSUPPORTED  int = 1 << 13
	LIBRAW_WARN_RAWSPEED_PROCESSED    int = 1 << 14
	LIBRAW_WARN_FALLBACK_TO_AHD       int = 1 << 15
	LIBRAW_WARN_PARSEFUJI_PROCESSED   int = 1 << 16
	LIBRAW_WARN_DNGSDK_PROCESSED      int = 1 << 17
	LIBRAW_WARN_DNG_IMAGES_REORDERED  int = 1 << 18
	LIBRAW_WARN_DNG_STAGE2_APPLIED    int = 1 << 19
	LIBRAW_WARN_DNG_STAGE3_APPLIED    int = 1 << 20
	LIBRAW_WARN_RAWSPEED3_PROBLEM     int = 1 << 21
	LIBRAW_WARN_RAWSPEED3_UNSUPPORTED int = 1 << 22
	LIBRAW_WARN_RAWSPEED3_PROCESSED   int = 1 << 23
	LIBRAW_WARN_RAWSPEED3_NOTLISTED   int = 1 << 24
	LIBRAW_WARN_VENDOR_CROP_SUGGESTED int = 1 << 25
	LIBRAW_WARN_DNG_NOT_PROCESSED     int = 1 << 26
	LIBRAW_WARN_DNG_NOT_PARSED        int = 1 << 27
)

// int constants mirror LibRaw enum LibRaw_whitebalance_code.
const (
	LIBRAW_WBI_Unknown         int = 0
	LIBRAW_WBI_Daylight        int = 1
	LIBRAW_WBI_Fluorescent     int = 2
	LIBRAW_WBI_Tungsten        int = 3
	LIBRAW_WBI_Flash           int = 4
	LIBRAW_WBI_FineWeather     int = 9
	LIBRAW_WBI_Cloudy          int = 10
	LIBRAW_WBI_Shade           int = 11
	LIBRAW_WBI_FL_D            int = 12
	LIBRAW_WBI_FL_N            int = 13
	LIBRAW_WBI_FL_W            int = 14
	LIBRAW_WBI_FL_WW           int = 15
	LIBRAW_WBI_FL_L            int = 16
	LIBRAW_WBI_Ill_A           int = 17
	LIBRAW_WBI_Ill_B           int = 18
	LIBRAW_WBI_Ill_C           int = 19
	LIBRAW_WBI_D55             int = 20
	LIBRAW_WBI_D65             int = 21
	LIBRAW_WBI_D75             int = 22
	LIBRAW_WBI_D50             int = 23
	LIBRAW_WBI_StudioTungsten  int = 24
	LIBRAW_WBI_Sunset          int = 64
	LIBRAW_WBI_Underwater      int = 65
	LIBRAW_WBI_FluorescentHigh int = 66
	LIBRAW_WBI_HT_Mercury      int = 67
	LIBRAW_WBI_AsShot          int = 81
	LIBRAW_WBI_Auto            int = 82
	LIBRAW_WBI_Custom          int = 83
	LIBRAW_WBI_Auto1           int = 85
	LIBRAW_WBI_Auto2           int = 86
	LIBRAW_WBI_Auto3           int = 87
	LIBRAW_WBI_Auto4           int = 88
	LIBRAW_WBI_Custom1         int = 90
	LIBRAW_WBI_Custom2         int = 91
	LIBRAW_WBI_Custom3         int = 92
	LIBRAW_WBI_Custom4         int = 93
	LIBRAW_WBI_Custom5         int = 94
	LIBRAW_WBI_Custom6         int = 95
	LIBRAW_WBI_PC_Set1         int = 96
	LIBRAW_WBI_PC_Set2         int = 97
	LIBRAW_WBI_PC_Set3         int = 98
	LIBRAW_WBI_PC_Set4         int = 99
	LIBRAW_WBI_PC_Set5         int = 100
	LIBRAW_WBI_Measured        int = 110
	LIBRAW_WBI_BW              int = 120
	LIBRAW_WBI_Kelvin          int = 254
	LIBRAW_WBI_Other           int = 255
	LIBRAW_WBI_None            int = 0xffff
)
